### ISSUE TITLE
Table 4 - missing reference?

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/st429-4#1]
for Gamma, the values are marked as:
```
urn:smpte:ul:060e2b34.04010108.04010101.01070000 (SMPTE-DC28 DCDM Transfer Characteristic)
```
Is there a reference for `SMPTE-DC28 DCDM Transfer Characteristic` or should it be a registered value?

**Comment by palemieux** [comment]
"SMPTE-DC28 DCDM Transfer Characteristic" is the name of the label in the registry. We can remove it if you think it is confusing.
